version: '3'
services:
  php:
    image: glagol/php:7.1-fpm-alpine-dev
    volumes:
      - ./out/:/var/www/html
      - ./config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      - APP_NAME=Glagol DSL Sandbox
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_LOG_LEVEL=debug
      - DB_HOST=mysql
      - DB_PASSWORD=123
    links:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=glagol
      - MYSQL_ROOT_PASSWORD=123
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  composer:
    image: composer:1.5
    entrypoint: ""
    command: /scripts/composer.sh
    volumes:
      - ./scripts/:/scripts
      - ./out/:/app
      - .composer/:/tmp

  nginx:
    image: nginx:1.13
    ports:
      - "8081:80"
    volumes:
      - ./config/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
