version: '3'
services:
  app:
    image: glagol/php:7.1-apache-dev
    volumes:
      - ./out/:/var/www/html
      - ./.composer_cache:/root/.composer/cache
    environment:
      - APP_NAME=Glagol DSL Sandbox
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_LOG_LEVEL=debug
      - DB_HOST=mysql
      - DB_PASSWORD=123
      - DOCTRINE_PROXY_PATH=/doctrine_proxies.d
    links:
      - mysql
    ports:
      - '8081:80'
    tmpfs:
      - /doctrine_proxies.d:rw,noexec,nosuid,mode=777

  mysql:
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=glagol
      - MYSQL_ROOT_PASSWORD=123
    volumes:
      - ./database:/docker-entrypoint-initdb.d
